// Auto-generated by Flutter
const serviceWorkerVersion = "version.json";
const baseHref = document.querySelector("base")?.getAttribute("href") ?? "/";
const bootstrap = () => {
  let src = "flutter.js";
  if (baseHref !== "/") src = baseHref + src;
  const script = document.createElement("script");
  script.src = src;
  script.defer = true;
  document.body.appendChild(script);
};
bootstrap();