import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'dart:io';

class PdfService {
  static Future<File> generatePatientPdf(Map patient) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        build: (pw.Context context) => pw.Center(
          child: pw.Column(
            children: [
              pw.Text("Patient Record", style: pw.TextStyle(fontSize: 30, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 40),
              pw.Text("Name: ${patient['name']}", style: const pw.TextStyle(fontSize: 20)),
              pw.Text("Age: ${patient['age'] ?? 'Not specified'}", style: const pw.TextStyle(fontSize: 20)),
              pw.Text("Condition: ${patient['condition'] ?? 'None'}", style: const pw.TextStyle(fontSize: 20)),
              pw.SizedBox(height: 40),
              pw.Text("Generated by MediRecords Pro", style: const pw.TextStyle(fontSize: 12)),
            ],
          ),
        ),
      ),
    );

    final dir = await getExternalStorageDirectory();
    final file = File("${dir!.path}/patient_${patient['id']}.pdf");
    await file.writeAsBytes(await pdf.save());
    return file;
  }
}